### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by panos** [Facepunch/sandbox#1]
Hi, I stumbled upon this repository and, in short, I'm pretty hyped with the fact that you're flipping the script in game development and doing everything transparently from the absolute beginning. I've already had a few ideas in a few areas that I'd like to work on and/or experiment with and, as such, I am particularly curious as to what's going to happen with the code in the repository license-wise, particularly because this issue could get very convoluted as soon as people start getting involved; As far as I know (not a lawyer, but I've been involved in free software development and had to deal with issues that arose from licenses), it's *technically* illegal for people to create their own forks or make modifications, and incorporating changes made by other people could eventually get very messy legal-wise and bring a lot of avoidable frustration.

While that could be overlooked, just like your organization seems to have done in the past with other repositories, I was wondering whether you'd believe that it would be a good idea to "nip that whole thing in the bud" from the beginning and assign an [OSI-approved license](https://opensource.org/licenses), a custom license (maybe a vanilla or slightly modified version of the [3-clause BSD license](https://opensource.org/licenses/BSD-3-Clause) that aims to restrict distribution could work? I'm not sure about what your business model is, so I'm just throwing that idea around as an example.) or a [**Contributor License Agreement**](https://en.wikipedia.org/wiki/Contributor_License_Agreement) in order to clarify that "You can do whatever (or not), we can distribute and sell that thing, you retain the rights to your code (or not)."

**Comment by akyudumsu** [comment]
bet you signed that stallman later

**Comment by Erlite** [comment]
What in the name of fuck.

**Comment by panos** [comment]
> bet you signed that stallman support letter

Funnily enough, it's actually the other way around, although I'd like to specifically avoid talking about that issue in order to avoid causing a flame war. (I probably wouldn't have a Steam account or be using GitHub, right?) Although I believe that free software is good for democracy as stated on my profile, I'm not trying to argue that all software *must* be free software or that I won't use it. (`I'm not sure what your business model is`)

I'm not sure why people are downvoting this to hell, but if this is going to be a *bit* free and allow people to contribute, it'd probably make sense to just clear up *how* free this should be. As far as the super-duper-free software side of things is concerned, [SuperTuxKart](https://github.com/supertuxkart/stk-code) cannot release their game on Steam legally, because they haven't been able to get *every single* contributor to agree to a license change from the [GNU GPL](https://github.com/supertuxkart/stk-code/blob/master/COPYING) to... the Mozilla Public License, if I'm correct? Or.., companies getting in a messy situation because they decided to implement code under the [MIT license](https://mit-license.org/) and forgot to give credit where it's due. I've seen people file DMCA claims against unlicensed repositories that made their own changes.

Point is, if I make a contribution and Facepunch wants to completely own it, release it on Steam and not pay me any money, (which I'd be personally fine with and it'd make sense and that's what's basically happening here, right?) that should be something that would be good to mention and that's what I tried to originally convey. If this is going to be "free", all I'm saying with the best intentions (rather trying to convince Garry to arbitrarily advance my own agenda with a video game with a sense of entitlement) is that it'd be good to define how *free* that otherwise already applies to other repositories (e.g. [Garry's Mod](https://github.com/Facepunch/garrysmod) as an unwritten rule.

**Comment by panos** [comment]
I'm pretty much just a starstruck kid whose adolescence was largely defined by Garry's Mod that wants to contribute to this and I'm just astonished (and, in all honesty, very much hyped :D) as to how good this could turn out to be. I promise that I have the best intentions and I'm not trying to convince a video game developer to advance a specific political agenda through concern trolling in an entitled manner, it's just that I've seen some issues arise in the past and decided to share my experience (which isn't that long either) so that bad things don't happen. Excuse me if I came off as aggressive earlier, I really tried my best.

**Comment by panos** [comment]
Thank you very much for addressing this, @garrynewman!
