### ISSUE TITLE
Spawning certain items.

### ISSUE THREAD

**Issue by NotGaylien** [Facepunch/sandbox#19]
Items like tables and such dont spawn right since the legs are far away from the origin it grabs the top of the table instead and spawns it partly in the ground.

The left is how it spawns currently. Right is how it should spawn.
![image](https://user-images.githubusercontent.com/82092361/128335068-6c23eb15-70ac-4934-88dd-155c9536b52d.png)

this issue i imagine would also occur with other models where the lowest hull is not near the centre.

Spawning from the origin probably also would not work well since some people make models with the origin in the exact centre of the model (for some reason)

**Comment by aylaylay** [comment]
Spawning how, in the sandbox gamemode?

**Comment by garrynewman** [comment]
We have this with the bench too. I think the spawning "fall to ground" code only traces down with the first physics object.

**Comment by aylaylay** [comment]
Should be better now

**Comment by NotGaylien** [comment]
all sorted, thanks guys!
