### ISSUE TITLE
Infinite spawning of PreviewEntity when having a tool deployed.

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sandbox#41]
Equipping a tool that has previews, for example the Balloon Tool, will produce infinite PreviewEntities spawning at the map origin, tanking the framerate when those entities are in PVS and crashing the game when the max limit is reached.

**Comment by aylaylay** [comment]
Likely a hotload bug

**Comment by Gmod4phun** [comment]
No idea, happens even with the game running in non-dev mode, right the first time, without reloading anything.

**Comment by aylaylay** [comment]
I've reworked how tools work
