### ISSUE TITLE
Spawn menu items not selectable behind chat messages

### ISSUE THREAD

**Issue by cashmen123** [Facepunch/sandbox#42]
### Describe the bug
In the spawn menu if you try to select items at the bottom left of the menu (S&Works tab currently has enough items to reproduce this) while people are talking in chat it blocks the items behind the chat boxes from being selected. Makes some items at the bottom of the list non-selectable in chatty servers.

### To Reproduce
- Load into a server
- Send a message through the chat
- Open the spawn menu and go to the S&Works tab
- Try to click any items positioned behind the chat message

### Expected behavior
Unless there's a reason to be able to click chat boxes, it'd be expected to be able to select the spawn menu item behind the message when mousing over it.

### Media/Files
Note: Hard to see the highlighting on the item but it's the can on the bottom left.
![20220730225854_1](https://user-images.githubusercontent.com/13245664/182007932-14a3063d-59a7-43d2-a68c-22f37955a7c6.jpg)
![20220730225859_1](https://user-images.githubusercontent.com/13245664/182007933-a3a8b96a-4140-48bf-abf8-44c4fdb38260.jpg)

**Comment by aylaylay** [comment]
We don't care that much about issues in this gamemode yet, however this is a simple fix so may as well.

**Comment by cashmen123** [comment]
Based, it's fixed thanks <3
