### ISSUE TITLE
What a error

### ISSUE THREAD

**Issue by pashaa812** [Facepunch/sandbox#77]
The following errors were found when trying to load the project: 

A 'using namespace' directive can only be applied to namespaces; 'Component' is a type not a namespace. Consider a 'using static' directive instead
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\tools\PhysGun.Effects.cs:2

The type or namespace name 'MenuSystem' does not exist in the namespace 'Sandbox' (are you missing an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Menu\MainMenu.razor:3

The type or namespace name 'DefaultGameMenu' does not exist in the namespace 'Sandbox.UI.GameMenu' (are you missing an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Menu\MainMenu.razor:7

The type or namespace name 'IUse' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\entities\ThrusterEntity.cs:5

The type or namespace name 'BaseCarriable' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Carriable.cs:4

The type or namespace name 'IUse' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Carriable.cs:4

The type or namespace name 'BaseWeapon' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Weapon.cs:5

The type or namespace name 'IUse' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Weapon.cs:5

The type or namespace name 'Entity' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\sandbox-master\code\Carriable.cs:23

**Comment by Kolya142** [comment]
what gamemode?
